language: node_js

sudo: required

node_js:
  - "6"
  - "6.1"
  - "6.2"
  - "6.3"
  - "6.4"
  - "6.5"
  - "6.6"
  - "6.7"
  - "6.8"
  - "6.9"
  - "7.0"
  - "7.1"
  - "7.2"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - export CXX="g++-4.8"
  - npm install -g npm@latest
  - npm install -g ethereumjs-testrpc truffle

install:
  - npm install 

script:
  - testrpc &
  - truffle test
